package com.optilive.tracker
import android.content.Intent
import android.os.Bundle
import android.webkit.WebView
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
class ClassificationActivity:AppCompatActivity(){
 override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_classification);findViewById<TextView>(R.id.subtitle).text="Clasificación en directo";findViewById<TextView>(R.id.navRanking).setTextColor(android.graphics.Color.parseColor("#1689E8"));val w=findViewById<WebView>(R.id.contentWeb);w.settings.javaScriptEnabled=true;w.settings.domStorageEnabled=true;w.loadDataWithBaseURL("https://optilive-node-production.up.railway.app",html(),"text/html","UTF-8",null);findViewById<TextView>(R.id.back).setOnClickListener{finish()};findViewById<TextView>(R.id.navMap).setOnClickListener{startActivity(Intent(this,MapActivity::class.java));finish()};findViewById<TextView>(R.id.navTracking).setOnClickListener{startActivity(Intent(this,TrackingActivity::class.java));finish()};findViewById<TextView>(R.id.navOptions).setOnClickListener{startActivity(Intent(this,MainActivity::class.java));finish()}}
 private fun html()="""<!doctype html><html lang="es"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;padding:16px;background:#f4f7fb;color:#193d50;font:15px system-ui}.card{background:white;border:1px solid #e0e8ef;border-radius:16px;padding:16px;margin-bottom:12px}h2{margin:0;font-size:20px}small,p{color:#607889}.row{padding:14px 0;border-top:1px solid #e7eef4;display:flex;justify-content:space-between}button,select{padding:10px;border-radius:10px;border:1px solid #dfe8ef;background:white;color:#193d50}</style><div class="card"><h2 id="race">Cargando regata…</h2><p id="detail"></p><small id="state"></small></div><div class="card"><b>Seguimiento GPS</b><p>Las posiciones GPS no constituyen una clasificación oficial. El orden de llegada todavía no está disponible.</p><select id="category" onchange="render()"><option value="">Todas las categorías</option><option>Sub11</option><option>Sub13</option><option>Sub15</option></select><div id="rows"></div></div><div class="card"><b>Resultados oficiales</b><p>Pendientes de publicación por la organización.</p></div><script>
let boats=[],active=false;const el=id=>document.getElementById(id);
function render(){const out=el('rows');out.replaceChildren();const selected=el('category').value;boats.filter(p=>!selected||p.category===selected).sort((a,b)=>String(a.sail).localeCompare(String(b.sail))).forEach(p=>{const row=document.createElement('div');row.className='row';const name=document.createElement('b');name.textContent=p.sail||'Barco';const meta=document.createElement('small');const age=Math.max(0,Math.round((Date.now()-(p.receivedAt||p.timestamp||0))/1000));meta.textContent=(age<30?'Señal reciente':'Señal antigua')+' · '+age+' s · '+Number(p.speedKnots||0).toFixed(1)+' kn';row.append(name,meta);out.append(row)});if(!out.children.length)out.textContent=selected?'No hay barcos con esta categoría registrada.':'No hay posiciones disponibles.'}
async function load(){try{const responses=await Promise.all([fetch('/api/regattas/current'),fetch('/api/boats')]);if(responses.some(r=>!r.ok))throw Error();const current=await responses[0].json();boats=await responses[1].json();active=!!current.race;el('race').textContent=current.regatta?.name||'Sin regata en curso';el('detail').textContent=active?(current.regatta.club||'')+' · Prueba '+current.race.number+' · Día '+current.race.day:'Selecciona una regata en la pestaña Regatas.';el('state').textContent=active?'Prueba en curso · seguimiento GPS':'Sin prueba activa';render()}catch(e){el('state').textContent='Sin conexión · los datos pueden estar desactualizados'}}load();setInterval(load,5000);
</script></html>"""
 override fun onPostCreate(b:Bundle?){super.onPostCreate(b);AppChrome.install(this,1,true)}
}
