package com.optilive.tracker
import android.content.Intent
import android.os.Bundle
import android.webkit.*
import android.widget.TextView
import android.os.Handler
import android.os.Looper
import java.net.URL
import org.json.JSONObject
import androidx.appcompat.app.AppCompatActivity
class MapActivity:AppCompatActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_map);val p=getSharedPreferences("optilive_profile",MODE_PRIVATE);var u=(p.getString("server_url","")?:"").trim();if(u.isNotBlank()&&!u.startsWith("http"))u="http://$u";findViewById<TextView>(R.id.raceName).text="Trofeo Fornells 2026";findViewById<TextView>(R.id.raceClub).text=p.getString("club","C.M. Mahón")?:"C.M. Mahón";findViewById<TextView>(R.id.liveStatus).text=if(u.isBlank())"● Sin conexión" else "● En directo";val w=findViewById<WebView>(R.id.webMap);w.settings.javaScriptEnabled=true;w.settings.domStorageEnabled=true;w.settings.mixedContentMode=WebSettings.MIXED_CONTENT_ALWAYS_ALLOW;w.loadUrl(if(u.isBlank())"https://optilive-node-production.up.railway.app" else u);loadWind(w);findViewById<TextView>(R.id.backTracking).setOnClickListener{finish()};findViewById<TextView>(R.id.zoomIn).setOnClickListener{w.evaluateJavascript("if(window.map)map.zoomIn()",null)};findViewById<TextView>(R.id.zoomOut).setOnClickListener{w.evaluateJavascript("if(window.map)map.zoomOut()",null)};findViewById<TextView>(R.id.centerMap).setOnClickListener{w.evaluateJavascript("if(window.focusLive)window.focusLive()",null)};findViewById<TextView>(R.id.classificationNav).setOnClickListener{startActivity(Intent(this,ClassificationActivity::class.java));finish()};findViewById<TextView>(R.id.trackingNav).setOnClickListener{startActivity(Intent(this,TrackingActivity::class.java));finish()};findViewById<TextView>(R.id.optionsNav).setOnClickListener{startActivity(Intent(this,MainActivity::class.java));finish()private fun loadWind(w:WebView){val out=findViewById<TextView>(R.id.windInfo);val h=Handler(Looper.getMainLooper());fun refresh(){w.evaluateJavascript("(function(){if(window.lastLive)return JSON.stringify(window.lastLive);return null})()"){raw->val cleaned=raw?.trim('"')?.replace("\\\"","\"");val a=Regex("-?[0-9]+(?:\\.[0-9]+)?").findAll(cleaned?:"").map{it.value.toDouble()}.toList();if(a.size>=2)Thread{try{val j=JSONObject(URL("https://api.open-meteo.com/v1/forecast?latitude="+a[0]+"&longitude="+a[1]+"&current=wind_speed_10m,wind_direction_10m,wind_gusts_10m&wind_speed_unit=kn").readText()).getJSONObject("current");val sp=j.getDouble("wind_speed_10m");val deg=j.getDouble("wind_direction_10m");val gust=j.optDouble("wind_gusts_10m",sp);val dirs=arrayOf("N","NE","E","SE","S","SO","O","NO");val dir=dirs[((deg+22.5)/45).toInt()%8];runOnUiThread{out.text="💨 %.1f kn  → %s  · R %.1f".format(sp,dir,gust)}}catch(e:Exception){runOnUiThread{out.text="💨 Viento no disponible"}}}.start()};h.postDelayed({refresh()},3000);h.postDelayed(object:Runnable{override fun run(){refresh();h.postDelayed(this,300000)}},300000)}}}}