package com.optilive.tracker
import android.content.Intent
import android.os.Bundle
import android.webkit.WebView
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
class TrackingActivity:AppCompatActivity(){
 override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_tracking);findViewById<TextView>(R.id.subtitle).text="Seguimiento de flota";findViewById<TextView>(R.id.navTracking).setTextColor(android.graphics.Color.parseColor("#1689E8"));val w=findViewById<WebView>(R.id.contentWeb);w.settings.javaScriptEnabled=true;w.settings.domStorageEnabled=true;w.loadDataWithBaseURL("https://optilive-node-production.up.railway.app",html(),"text/html","UTF-8",null);findViewById<TextView>(R.id.back).setOnClickListener{finish()};findViewById<TextView>(R.id.navMap).setOnClickListener{startActivity(Intent(this,MapActivity::class.java));finish()};findViewById<TextView>(R.id.navRanking).setOnClickListener{startActivity(Intent(this,ClassificationActivity::class.java));finish()};findViewById<TextView>(R.id.navOptions).setOnClickListener{startActivity(Intent(this,MainActivity::class.java));finish()}}
 private fun html()="""<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'><style>
*{box-sizing:border-box}body{margin:0;background:#f4f7fb;color:#193d50;font-family:Arial}.toolbar{position:sticky;top:0;background:#fff;padding:10px;z-index:2}.search{width:100%;padding:12px;border:0;border-radius:7px;background:#edf3f7;color:#193d50;font-size:16px}.tabs{display:flex;margin-top:8px}.tabs button{flex:1;padding:9px;border:0;background:#16313b;color:#b9cbd2;font-weight:800}.tabs .on{background:#08a4c5;color:#fff}.head,.row{display:grid;grid-template-columns:46px 105px 1fr 62px 62px;align-items:center}.head{background:#08a4c5;padding:9px 6px;font-size:12px;font-weight:800}.row{min-height:47px;padding:5px 6px;border-bottom:1px solid #dfe8ef;font-size:14px}.row:nth-child(even){background:#edf3f7}.rank{width:35px;height:32px;border-radius:3px;display:flex;align-items:center;justify-content:center;font-weight:900;background:#087fe3}.sail{font-weight:800}.name{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.num{text-align:right;font-weight:700}.muted{color:#9bb0b8}.empty{padding:35px;text-align:center;color:#9bb0b8}
</style></head><body><div class='toolbar'><input id='q' class='search' placeholder='Buscar vela o regatista…' oninput='render()'><div class='tabs'><button id='dataTab' class='on' onclick='mode="data";tabs();render()'>DATOS</button><button id='nameTab' onclick='mode="name";tabs();render()'>REGATISTA</button></div></div><div id='head'></div><div id='list'><div class='empty'>Buscando barcos…</div></div><script>
let boats=[],mode='data',marks=[];function rad(x){return x*Math.PI/180}function d(a,b){let R=6371000,p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lon-a.lon);let q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}function enrich(){if(marks.length<2)return boats.map(p=>({...p,distanceToNext:null,progress:null}));return boats.map(p=>{let best={progress:-1,distanceToNext:null};for(let i=0;i<marks.length-1;i++){let a=marks[i],b=marks[i+1],ab=d(a,b);if(!ab)continue;let ap=d(a,p),bp=d(b,p),along=Math.max(0,Math.min(ab,(ap*ap+ab*ab-bp*bp)/(2*ab)));let cross=Math.sqrt(Math.max(0,ap*ap-along*along));let prior=0;for(let j=0;j<i;j++)prior+=d(marks[j],marks[j+1]);let score=prior+along-cross*.25;if(score>best.progress)best={progress:score,distanceToNext:bp}}return {...p,...best}}).sort((a,b)=>(b.progress??-1)-(a.progress??-1))}function tabs(){dataTab.className=mode==='data'?'on':'';nameTab.className=mode==='name'?'on':''}
function esc(x){return String(x==null?'':x).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function render(){let q=document.getElementById('q').value.toLowerCase(),b=boats.map(p=>({...p,distanceToNext:null})).filter(p=>(String(p.sail||'')+' '+String(p.name||p.sailor||'')).toLowerCase().includes(q));head.innerHTML=mode==='data'?'<div class="head"><span>#</span><span>VELA</span><span>DIST.</span><span>KTS</span><span>RUMBO</span></div>':'<div class="head"><span>#</span><span>VELA</span><span>REGATISTA</span><span></span><span></span></div>';let h='';b.forEach((p,i)=>{let sp=p.speedKnots==null?'--':Number(p.speedKnots).toFixed(1),hd=p.heading==null?(p.bearing==null?'--':Math.round(p.bearing)+'°'):Math.round(p.heading)+'°',dist=p.distanceToNext==null?'--':Math.round(p.distanceToNext)+'m',name=p.name||p.sailor||'—';h+=mode==='data'?'<div class="row"><span class="rank">'+'—'+'</span><span class="sail">'+esc(p.sail)+'</span><span>'+dist+'</span><span class="num">'+sp+'</span><span class="num">'+hd+'</span></div>':'<div class="row"><span class="rank">'+'—'+'</span><span class="sail">'+esc(p.sail)+'</span><span class="name">'+esc(name)+'</span><span></span><span></span></div>'});list.innerHTML=h||'<div class="empty">No hay barcos transmitiendo</div>'}
async function load(){try{let [rb,rr]=await Promise.all([fetch('/api/boats'),fetch('/api/regattas')]);boats=await rb.json();let regs=await rr.json();if(regs.length){let rm=await fetch('/api/regattas/'+regs[regs.length-1].id+'/marks');marks=(await rm.json()).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lon)).sort((a,b)=>(a.courseOrder??a.updatedAt??0)-(b.courseOrder??b.updatedAt??0))}render()}catch(e){list.innerHTML='<div class="empty">Sin conexión con el servidor</div>'}}load();setInterval(load,2500)
</script></body></html>"""

 override fun onPostCreate(b:Bundle?){super.onPostCreate(b);AppChrome.install(this,1,true)}
}