package com.optilive.tracker
import android.content.Intent
import android.os.Bundle
import android.webkit.WebView
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
class TrackingActivity:AppCompatActivity(){
 override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_tracking);findViewById<TextView>(R.id.subtitle).text="Seguimiento de flota";findViewById<TextView>(R.id.navTracking).setTextColor(android.graphics.Color.parseColor("#1689E8"));val w=findViewById<WebView>(R.id.contentWeb);w.settings.javaScriptEnabled=true;w.settings.domStorageEnabled=true;w.loadDataWithBaseURL("https://optilive-node-production.up.railway.app",html(),"text/html","UTF-8",null);findViewById<TextView>(R.id.back).setOnClickListener{finish()};findViewById<TextView>(R.id.navMap).setOnClickListener{startActivity(Intent(this,MapActivity::class.java));finish()};findViewById<TextView>(R.id.navRanking).setOnClickListener{startActivity(Intent(this,ClassificationActivity::class.java));finish()};findViewById<TextView>(R.id.navOptions).setOnClickListener{startActivity(Intent(this,MainActivity::class.java));finish()}}
 private fun html()="""<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'><style>*{box-sizing:border-box}body{margin:0;background:#f4f7fa;font-family:Arial;color:#172433;padding:12px}.summary,.boat{background:#fff;border-radius:16px;box-shadow:0 2px 12px #16334b18}.summary{padding:15px;margin-bottom:12px}.title{font-size:18px;font-weight:800}.sub{color:#6a7887;font-size:13px;margin-top:4px}.live{float:right;color:#0aa573;font-size:12px;font-weight:800}.boat{padding:14px;margin-bottom:10px}.top{display:flex;align-items:center}.badge{width:44px;height:44px;border-radius:50%;background:#e8f4fd;color:#087fe3;display:flex;align-items:center;justify-content:center;font-weight:900;margin-right:12px}.grow{flex:1}.sail{font-size:17px;font-weight:800}.meta{font-size:11px;color:#748292;margin-top:3px}.online{color:#0aa573;font-size:11px;font-weight:800}.stats{display:grid;grid-template-columns:1fr 1fr 1fr;margin-top:12px;padding-top:10px;border-top:1px solid #edf1f4}.stat{text-align:center;font-size:11px;color:#748292}.stat b{display:block;color:#1d3448;font-size:15px;margin-bottom:3px}.empty{padding:28px;text-align:center;color:#748292}</style></head><body><div class='summary'><span class='live'>● LIVE</span><div class='title'>Seguimiento</div><div class='sub'><span id='count'>0</span> barcos conectados · actualización automática</div></div><div id='boats'><div class='empty'>Buscando barcos…</div></div><script>async function load(){try{var r=await fetch('/api/boats');var b=await r.json();document.getElementById('count').textContent=b.length;var h='';b.forEach(function(p){var age=Math.max(0,Math.round((Date.now()-(p.receivedAt||p.timestamp||Date.now()))/1000));var acc=p.accuracy==null?'--':Math.round(p.accuracy)+' m';var sp=p.speedKnots==null?'0.0':Number(p.speedKnots).toFixed(1);h+='<div class="boat"><div class="top"><div class="badge">⛵</div><div class="grow"><div class="sail">'+p.sail+'</div><div class="meta">Última posición hace '+age+' s</div></div><div class="online">● CONECTADO</div></div><div class="stats"><div class="stat"><b>'+sp+' kn</b>Velocidad</div><div class="stat"><b>'+acc+'</b>Precisión GPS</div><div class="stat"><b>'+age+'s</b>Última señal</div></div></div>'});document.getElementById('boats').innerHTML=h||'<div class="empty">No hay barcos transmitiendo</div>'}catch(e){document.getElementById('boats').innerHTML='<div class="empty">Sin conexión con el servidor</div>'}}load();setInterval(load,2500)</script></body></html>"""
}